
kind: pipeline
name: java8

platform:
  arch: amd64

steps:
- name: prepare-dependencies
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-dl-java mvncentral/org.json:json:20211205
  - artifact-dl-java omz/org.omegazero.common:omz-common:latest
  - artifact-dl-java omz/org.omegazero.net:omz-netlib-common:latest

- name: prepare-source
  image: omz-ci-tools
  pull: never
  commands:
  - mkdir build
  - setversion http-core/main/java/org/omegazero/http/HTTPLib.java
  - curl -G "https://omegazero.org/site/software/r/license_bin_full.php" --data-urlencode "srcurl=$DRONE_REPO_LINK/src/commit/$DRONE_COMMIT" > LICENSE_BIN

- name: build-core
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http-core/META-INF
  - cp LICENSE_BIN build/http-core/META-INF/LICENSE
  - make core BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: build-net
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http-net/META-INF
  - cp LICENSE_BIN build/http-net/META-INF/LICENSE
  - make net BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source
  - build-core

- name: build-http1
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http1/META-INF
  - cp LICENSE_BIN build/http1/META-INF/LICENSE
  - make http1 BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source
  - build-core

- name: build-http2
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/http2/META-INF
  - cp LICENSE_BIN build/http2/META-INF/LICENSE
  - make http2 BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source
  - build-core

- name: build-all
  image: openjdk:8
  commands:
  - mkdir -p build/all/META-INF
  - cp -r build/http-core/* build/http-net/* build/http1/* build/http2/* build/all
  - cp LICENSE_BIN build/all/META-INF/LICENSE
  - jar cf build-all.jar -C build/all .
  depends_on:
  - build-core
  - build-net
  - build-http1
  - build-http2

- name: publish
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-push-java build-all.jar omz/org.omegazero.http:omz-http
  - artifact-push-java build/http-core.jar omz/org.omegazero.http:omz-http-core
  - artifact-push-java build/http-net.jar omz/org.omegazero.http:omz-http-net
  - artifact-push-java build/http1.jar omz/org.omegazero.http:omz-http-http1
  - artifact-push-java build/http2.jar omz/org.omegazero.http:omz-http-http2
  depends_on:
  - build-all
  environment:
    OMZ_ARTIFACT_PUSH_TOKEN:
      from_secret: artifact_push_token
